In [1]:
import pandas as pd

In [2]:
join_keys = ["GeoID", "Borough"]

In [4]:
internet = pd.read_csv("./data/raw/Internet_Master_Plan__Adoption_and_Infrastructure_Data_by_Neighborhood.csv")
internet["GeoID"] = internet["Neighborhood Tabulation Area Code (NTA Code)"]
internet["Borough"] = internet["Borough Name"]
internet.drop(columns=["Neighborhood Tabulation Area Code (NTA Code)", "Borough Name"], inplace=True)
internet["Borough"] = internet.apply(lambda row: row.Borough if row.Borough != "Bronx" else "The Bronx", axis = 1)
internet.rename(inplace=True, columns={c: 'internet_'+c for c in internet.columns if c not in join_keys})
internet

,internet_Neighborhood Tabulation Area Name (NTA NAME),internet_Total Population,internet_Population Density (per Sq. Mi.),internet_Total Number of Households,internet_Area (Sq. Mi.),internet_Street Mileage,internet_Home Broadband Adoption (Percentage of Households),"internet_Home Broadband Adoption by Quartiles (High, Medium-High, Medium-Low, Low)",internet_Mobile Broadband Adoption (Percentage of Households),"internet_Mobile broadband adoption by Quartiles (High, Medium-High, Medium-Low, Low)",...,internet_Percentage Optimal for Unlicensed\nMillimeter Wave Fixed Wireless Access as a Residential\nBroadband Solution,internet_Estimated number of radio sites for CBRS coverage,internet_Estimated number of radio sites for mmWave coverage in optimal areas,internet_Sample of NTA Field Surveyed? (Y/N),internet_Reviewed for Underground Fiber-to-the-Premise? (Y/N),internet_Reviewed for Aerial Fiber-to-the-Premise? (Y/N),internet_Reviewed for Millimeter Wave Fixed Wireless Access? (Y/N),internet_Field Survey Findings,GeoID,Borough
0,Brooklyn Heights-Cobble Hill,23758,65994.44,11150,0.36,19,0.8640,High Connected,0.8820,High Connected,...,0.37,174.0,39.0,NO,NO,NO,NO,NONE,BK09,Brooklyn
1,Sheepshead Bay-Gerritsen Beach-Manhattan Beach,65167,28707.93,25483,2.27,80,0.7729,Medium High Connected,0.7604,Low Connected,...,0.25,86.0,29.0,NO,NO,NO,NO,NONE,BK17,Brooklyn
2,Brighton Beach,34814,56151.61,14441,0.62,23,0.6653,Medium Low Connected,0.6880,Low Connected,...,0.62,56.0,8.0,NO,NO,NO,NO,NONE,BK19,Brooklyn
3,Seagate-Coney Island,31120,22388.49,11553,1.39,25,0.5547,Low Connected,0.6092,Low Connected,...,0.36,82.0,0.0,YES,NO,YES,YES,Low make-ready requirements. Some locations ha...,BK21,Brooklyn
4,West Brighton,17252,55651.61,8547,0.31,12,0.6682,Medium Low Connected,0.6754,Low Connected,...,0.37,185.0,35.0,NO,NO,NO,NO,NONE,BK23,Brooklyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Stapleton-Rosebank,25281,15138.32,9196,1.67,50,0.6903,Medium Low Connected,0.7075,Low Connected,...,0.10,128.0,12.0,NO,NO,NO,NO,NONE,SI37,Staten Island
191,New Dorp-Midland Beach,21208,10657.29,7856,1.99,53,0.7668,Medium High Connected,0.7503,Low Connected,...,0.00,152.0,0.0,NO,NO,NO,NO,NONE,SI45,Staten Island
192,Arden Heights,26887,14854.70,9054,1.81,40,0.8120,High Connected,0.8383,High Connected,...,0.00,139.0,0.0,NO,NO,NO,NO,NONE,SI48,Staten Island
193,Great Kills,41724,12998.13,15081,3.21,79,0.7913,High Connected,0.8090,Medium High Connected,...,0.00,246.0,0.0,NO,NO,NO,NO,NONE,SI54,Staten Island
194,park-cemetery-etc-Staten Island,0,0.00,0,0.86,8,0.0000,Low Connected,0.0000,Low Connected,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SI99,Staten Island

In [5]:
soc = pd.read_excel("./data/raw/ACS5yrNTA/soc_2016acs5yr_nta.xlsx", sheet_name="SocData")
soc.rename(inplace=True, columns={c: 'soc_'+c for c in soc.columns if c not in join_keys})
soc

,soc_GeoType,soc_GeogName,GeoID,Borough,soc_HH1E,soc_HH1M,soc_HH1C,soc_HH1P,soc_HH1Z,soc_Fam1E,...,soc_OthrE,soc_OthrM,soc_OthrC,soc_OthrP,soc_OthrZ,soc_UnclsNRE,soc_UnclsNRM,soc_UnclsNRC,soc_UnclsNRP,soc_UnclsNRZ
0,NTA2010,Bath Beach,BK27,Brooklyn,11428,209.0,1.1,100.0,NaN,8207,...,15051,1186.0,4.8,45.4,3.1,6697,1100.0,10.0,20.2,3.2
1,NTA2010,Bay Ridge,BK31,Brooklyn,33487,442.0,0.8,100.0,NaN,18935,...,27814,1530.0,3.3,35.1,1.8,7423,806.0,6.6,9.4,1.0
2,NTA2010,Bedford,BK75,Brooklyn,26059,401.0,0.9,100.0,NaN,14540,...,41891,1898.0,2.8,55.6,2.0,9693,1035.0,6.5,12.9,1.3
3,NTA2010,Bensonhurst East,BK29,Brooklyn,22187,338.0,0.9,100.0,NaN,16276,...,34121,1732.0,3.1,53.1,2.3,9077,1007.0,6.7,14.1,1.5
4,NTA2010,Bensonhurst West,BK28,Brooklyn,29909,364.0,0.7,100.0,NaN,21832,...,47340,1974.0,2.5,51.7,1.8,15409,1377.0,5.4,16.8,1.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,NTA2010,West Concourse,BX63,The Bronx,13095,216.0,1.0,100.0,NaN,8516,...,29227,1478.0,3.1,78.2,2.6,3362,664.0,12.0,9.0,1.7
191,NTA2010,West Farms-Bronx River,BX08,The Bronx,11865,255.0,1.3,100.0,NaN,8115,...,27566,1516.0,3.3,77.1,2.8,2735,530.0,11.8,7.6,1.4
192,NTA2010,Westchester-Unionport,BX59,The Bronx,9073,212.0,1.4,100.0,NaN,6317,...,21988,1318.0,3.6,77.3,3.2,2643,504.0,11.6,9.3,1.7
193,NTA2010,Williamsbridge-Olinville,BX44,The Bronx,21483,292.0,0.8,100.0,NaN,14627,...,28686,1602.0,3.4,44.1,2.1,6252,803.0,7.8,9.6,1.2
194,NTA2010,Woodlawn-Wakefield,BX62,The Bronx,14863,263.0,1.1,100.0,NaN,10361,...,15237,1249.0,5.0,34.6,2.6,4895,751.0,9.3,11.1,1.7

In [6]:
demo = pd.read_excel("./data/raw/ACS5yrNTA/demo_2016acs5yr_nta.xlsx", sheet_name="DemData")
demo.rename(inplace=True, columns={c: 'demo_'+c for c in demo.columns if c not in join_keys})
demo

,demo_GeoType,demo_GeogName,GeoID,Borough,demo_Pop_1E,demo_Pop_1M,demo_Pop_1C,demo_Pop_1P,demo_Pop_1Z,demo_MaleE,...,demo_AsnOAsnE,demo_AsnOAsnM,demo_AsnOAsnC,demo_AsnOAsnP,demo_AsnOAsnZ,demo_Asn2plE,demo_Asn2plM,demo_Asn2plC,demo_Asn2plP,demo_Asn2plZ
0,NTA2010,Bath Beach,BK27,Brooklyn,33163,1246.0,2.3,100.0,NaN,16686,...,47,42.0,54.9,0.4,0.3,152,103.0,41.4,1.3,0.8
1,NTA2010,Bay Ridge,BK31,Brooklyn,79134,1724.0,1.3,100.0,NaN,37829,...,113,113.0,60.9,1.0,1.0,93,61.0,40.2,0.8,0.5
2,NTA2010,Bedford,BK75,Brooklyn,75318,1993.0,1.6,100.0,NaN,36491,...,26,29.0,67.8,1.1,1.2,56,52.0,56.7,2.4,2.2
3,NTA2010,Bensonhurst East,BK29,Brooklyn,64267,1675.0,1.6,100.0,NaN,31283,...,47,57.0,73.2,0.2,0.2,232,175.0,45.9,0.9,0.7
4,NTA2010,Bensonhurst West,BK28,Brooklyn,91646,1975.0,1.3,100.0,NaN,44651,...,279,190.0,41.5,0.7,0.5,428,202.0,28.7,1.1,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,NTA2010,West Concourse,BX63,The Bronx,37395,1423.0,2.3,100.0,NaN,17966,...,39,54.0,84.7,5.6,7.5,0,NaN,NaN,NaN,NaN
191,NTA2010,West Farms-Bronx River,BX08,The Bronx,35752,1461.0,2.5,100.0,NaN,17105,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
192,NTA2010,Westchester-Unionport,BX59,The Bronx,28437,1232.0,2.6,100.0,NaN,13282,...,39,50.0,78.1,1.1,1.4,67,97.0,88.4,1.9,2.7
193,NTA2010,Williamsbridge-Olinville,BX44,The Bronx,65043,1793.0,1.7,100.0,NaN,30020,...,11,13.0,74.1,1.4,1.6,0,NaN,NaN,NaN,NaN
194,NTA2010,Woodlawn-Wakefield,BX62,The Bronx,44064,1442.0,2.0,100.0,NaN,20502,...,0,NaN,NaN,NaN,NaN,11,17.0,93.9,0.6,0.9

In [7]:
econ = pd.read_excel("./data/raw/ACS5yrNTA/econ_2016acs5yr_nta.xlsx", sheet_name="EconData")
econ.rename(inplace=True, columns={c: 'econ_'+c for c in econ.columns if c not in join_keys})
econ

,econ_GeoType,econ_GeogName,GeoID,Borough,econ_Pop16plE,econ_Pop16plM,econ_Pop16plC,econ_Pop16plP,econ_Pop16plZ,econ_LFE,...,econ_Pv400t499E,econ_Pv400t499M,econ_Pv400t499C,econ_Pv400t499P,econ_Pv400t499Z,econ_Pv500plE,econ_Pv500plM,econ_Pv500plC,econ_Pv500plP,econ_Pv500plZ
0,NTA2010,Bath Beach,BK27,Brooklyn,26855,943.0,2.1,100.0,NaN,16006,...,3464,434.0,7.6,10.5,1.3,8268,599.0,4.4,25.1,1.6
1,NTA2010,Bay Ridge,BK31,Brooklyn,65479,1260.0,1.2,100.0,NaN,42176,...,7564,572.0,4.6,9.6,0.7,28491,1041.0,2.2,36.1,1.1
2,NTA2010,Bedford,BK75,Brooklyn,54904,1390.0,1.5,100.0,NaN,36993,...,5175,561.0,6.6,6.9,0.7,12144,846.0,4.2,16.2,1.0
3,NTA2010,Bensonhurst East,BK29,Brooklyn,52857,1307.0,1.5,100.0,NaN,32004,...,5634,522.0,5.6,8.8,0.8,12868,812.0,3.8,20.1,1.2
4,NTA2010,Bensonhurst West,BK28,Brooklyn,74470,1568.0,1.3,100.0,NaN,45842,...,7969,641.0,4.9,8.7,0.7,17583,934.0,3.2,19.2,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,NTA2010,West Concourse,BX63,The Bronx,28216,1115.0,2.4,100.0,NaN,17183,...,2236,384.0,10.4,6.0,1.0,1887,370.0,11.9,5.1,1.0
191,NTA2010,West Farms-Bronx River,BX08,The Bronx,27277,1103.0,2.5,100.0,NaN,16011,...,2140,409.0,11.6,6.0,1.1,2317,440.0,11.5,6.5,1.2
192,NTA2010,Westchester-Unionport,BX59,The Bronx,22508,968.0,2.6,100.0,NaN,13869,...,1924,340.0,10.7,6.9,1.2,4526,478.0,6.4,16.1,1.5
193,NTA2010,Williamsbridge-Olinville,BX44,The Bronx,50582,1398.0,1.7,100.0,NaN,32203,...,6260,597.0,5.8,9.7,0.9,8962,682.0,4.6,14.0,1.0
194,NTA2010,Woodlawn-Wakefield,BX62,The Bronx,35865,1158.0,2.0,100.0,NaN,23542,...,4003,471.0,7.2,9.1,1.0,11328,802.0,4.3,25.8,1.6

In [8]:
housing = pd.read_excel("./data/raw/ACS5yrNTA/hous_2016acs5yr_nta.xlsx", sheet_name="HousData")
housing.rename(inplace=True, columns={c: 'housing_'+c for c in housing.columns if c not in join_keys})
housing

,housing_GeoType,housing_GeogName,GeoID,Borough,housing_HU1E,housing_HU1M,housing_HU1C,housing_HU1P,housing_HU1Z,housing_OcHU1E,...,housing_GRPI50plE,housing_GRPI50plM,housing_GRPI50plC,housing_GRPI50plP,housing_GRPI50plZ,housing_GRPINtCE,housing_GRPINtCM,housing_GRPINtCC,housing_GRPINtCP,housing_GRPINtCZ
0,NTA2010,Bath Beach,BK27,Brooklyn,12090,156.0,0.8,100.0,NaN,11428,...,1975,244.0,7.5,30.0,3.5,379,104.0,16.7,NaN,NaN
1,NTA2010,Bay Ridge,BK31,Brooklyn,37242,295.0,0.5,100.0,NaN,33487,...,5640,427.0,4.6,27.8,2.0,1165,224.0,11.7,NaN,NaN
2,NTA2010,Bedford,BK75,Brooklyn,29106,251.0,0.5,100.0,NaN,26059,...,6226,458.0,4.5,30.9,2.1,1070,216.0,12.3,NaN,NaN
3,NTA2010,Bensonhurst East,BK29,Brooklyn,23851,240.0,0.6,100.0,NaN,22187,...,4400,385.0,5.3,32.6,2.6,1055,200.0,11.5,NaN,NaN
4,NTA2010,Bensonhurst West,BK28,Brooklyn,31701,284.0,0.5,100.0,NaN,29909,...,5862,435.0,4.5,31.6,2.2,1039,192.0,11.2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,NTA2010,West Concourse,BX63,The Bronx,13741,109.0,0.5,100.0,NaN,13095,...,5197,405.0,4.7,42.8,3.2,638,179.0,17.1,NaN,NaN
191,NTA2010,West Farms-Bronx River,BX08,The Bronx,12876,149.0,0.7,100.0,NaN,11865,...,3722,376.0,6.1,40.1,3.7,774,229.0,18.0,NaN,NaN
192,NTA2010,Westchester-Unionport,BX59,The Bronx,9669,131.0,0.8,100.0,NaN,9073,...,2689,309.0,7.0,41.8,4.4,308,98.0,19.3,NaN,NaN
193,NTA2010,Williamsbridge-Olinville,BX44,The Bronx,23090,193.0,0.5,100.0,NaN,21483,...,5566,414.0,4.5,39.0,2.6,858,187.0,13.2,NaN,NaN
194,NTA2010,Woodlawn-Wakefield,BX62,The Bronx,15857,171.0,0.7,100.0,NaN,14863,...,2436,288.0,7.2,32.8,3.5,502,140.0,17.0,NaN,NaN

In [9]:
data = internet
for right in [soc, demo, housing, econ]:
    data = data.merge(right, on=["GeoID", "Borough"], how="left")
data

,internet_Neighborhood Tabulation Area Name (NTA NAME),internet_Total Population,internet_Population Density (per Sq. Mi.),internet_Total Number of Households,internet_Area (Sq. Mi.),internet_Street Mileage,internet_Home Broadband Adoption (Percentage of Households),"internet_Home Broadband Adoption by Quartiles (High, Medium-High, Medium-Low, Low)",internet_Mobile Broadband Adoption (Percentage of Households),"internet_Mobile broadband adoption by Quartiles (High, Medium-High, Medium-Low, Low)",...,econ_Pv400t499E,econ_Pv400t499M,econ_Pv400t499C,econ_Pv400t499P,econ_Pv400t499Z,econ_Pv500plE,econ_Pv500plM,econ_Pv500plC,econ_Pv500plP,econ_Pv500plZ
0,Brooklyn Heights-Cobble Hill,23758,65994.44,11150,0.36,19,0.8640,High Connected,0.8820,High Connected,...,1583,310.0,11.9,7.1,1.4,14382,817.0,3.5,64.4,2.6
1,Sheepshead Bay-Gerritsen Beach-Manhattan Beach,65167,28707.93,25483,2.27,80,0.7729,Medium High Connected,0.7604,Low Connected,...,7387,705.0,5.8,11.2,1.0,18824,956.0,3.1,28.5,1.2
2,Brighton Beach,34814,56151.61,14441,0.62,23,0.6653,Medium Low Connected,0.6880,Low Connected,...,2401,375.0,9.5,7.1,1.1,7733,719.0,5.7,22.8,1.9
3,Seagate-Coney Island,31120,22388.49,11553,1.39,25,0.5547,Low Connected,0.6092,Low Connected,...,1552,310.0,12.1,5.3,1.0,3473,453.0,7.9,12.0,1.5
4,West Brighton,17252,55651.61,8547,0.31,12,0.6682,Medium Low Connected,0.6754,Low Connected,...,1677,385.0,14.0,10.6,2.4,4687,588.0,7.6,29.8,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Stapleton-Rosebank,25281,15138.32,9196,1.67,50,0.6903,Medium Low Connected,0.7075,Low Connected,...,2778,396.0,8.7,10.9,1.5,6128,541.0,5.4,24.0,1.9
191,New Dorp-Midland Beach,21208,10657.29,7856,1.99,53,0.7668,Medium High Connected,0.7503,Low Connected,...,3108,459.0,9.0,14.6,2.0,8343,654.0,4.8,39.1,2.2
192,Arden Heights,26887,14854.70,9054,1.81,40,0.8120,High Connected,0.8383,High Connected,...,3333,551.0,10.0,12.6,2.0,11557,863.0,4.5,43.7,2.9
193,Great Kills,41724,12998.13,15081,3.21,79,0.7913,High Connected,0.8090,Medium High Connected,...,6455,675.0,6.4,14.8,1.5,19033,1114.0,3.6,43.7,2.3
194,park-cemetery-etc-Staten Island,0,0.00,0,0.86,8,0.0000,Low Connected,0.0000,Low Connected,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

In [11]:
len(data.columns) == (
    len(housing.columns) +
    len(econ.columns) +
    len(demo.columns) +
    len(soc.columns) +
    len(internet.columns) - 8)

True

In [12]:
for col_name in ["Borough", "GeoID"]:
    col = data.pop(col_name)
    data.insert(0, col_name, col)
data

/var/folders/8t/53h96trd3rxf1czhhkwp3h_m0000gn/T/ipykernel_78876/3689601434.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data.insert(0, col_name, col)
/var/folders/8t/53h96trd3rxf1czhhkwp3h_m0000gn/T/ipykernel_78876/3689601434.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data.insert(0, col_name, col)

,GeoID,Borough,internet_Neighborhood Tabulation Area Name (NTA NAME),internet_Total Population,internet_Population Density (per Sq. Mi.),internet_Total Number of Households,internet_Area (Sq. Mi.),internet_Street Mileage,internet_Home Broadband Adoption (Percentage of Households),"internet_Home Broadband Adoption by Quartiles (High, Medium-High, Medium-Low, Low)",...,econ_Pv400t499E,econ_Pv400t499M,econ_Pv400t499C,econ_Pv400t499P,econ_Pv400t499Z,econ_Pv500plE,econ_Pv500plM,econ_Pv500plC,econ_Pv500plP,econ_Pv500plZ
0,BK09,Brooklyn,Brooklyn Heights-Cobble Hill,23758,65994.44,11150,0.36,19,0.8640,High Connected,...,1583,310.0,11.9,7.1,1.4,14382,817.0,3.5,64.4,2.6
1,BK17,Brooklyn,Sheepshead Bay-Gerritsen Beach-Manhattan Beach,65167,28707.93,25483,2.27,80,0.7729,Medium High Connected,...,7387,705.0,5.8,11.2,1.0,18824,956.0,3.1,28.5,1.2
2,BK19,Brooklyn,Brighton Beach,34814,56151.61,14441,0.62,23,0.6653,Medium Low Connected,...,2401,375.0,9.5,7.1,1.1,7733,719.0,5.7,22.8,1.9
3,BK21,Brooklyn,Seagate-Coney Island,31120,22388.49,11553,1.39,25,0.5547,Low Connected,...,1552,310.0,12.1,5.3,1.0,3473,453.0,7.9,12.0,1.5
4,BK23,Brooklyn,West Brighton,17252,55651.61,8547,0.31,12,0.6682,Medium Low Connected,...,1677,385.0,14.0,10.6,2.4,4687,588.0,7.6,29.8,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,SI37,Staten Island,Stapleton-Rosebank,25281,15138.32,9196,1.67,50,0.6903,Medium Low Connected,...,2778,396.0,8.7,10.9,1.5,6128,541.0,5.4,24.0,1.9
191,SI45,Staten Island,New Dorp-Midland Beach,21208,10657.29,7856,1.99,53,0.7668,Medium High Connected,...,3108,459.0,9.0,14.6,2.0,8343,654.0,4.8,39.1,2.2
192,SI48,Staten Island,Arden Heights,26887,14854.70,9054,1.81,40,0.8120,High Connected,...,3333,551.0,10.0,12.6,2.0,11557,863.0,4.5,43.7,2.9
193,SI54,Staten Island,Great Kills,41724,12998.13,15081,3.21,79,0.7913,High Connected,...,6455,675.0,6.4,14.8,1.5,19033,1114.0,3.6,43.7,2.3
194,SI99,Staten Island,park-cemetery-etc-Staten Island,0,0.00,0,0.86,8,0.0000,Low Connected,...,0,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

In [13]:
data.to_csv("./data/clean/combined_dataset.csv", index=False)